[programs.mainnet]
raffle = "CMty9AbXpbVnuQZ6q7NwPF13yTaBBrByL2K6bmsVTVgq"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
